import {
  ArcRotateCamera, Color3, Color4, DirectionalLight, Engine, HemisphericLight,
  Mesh, MeshBuilder, PBRMaterial, Scene, ShadowGenerator, StandardMaterial,
  TransformNode, Vector3
} from '@babylonjs/core';

type Captain={id:string;name:string;style:string;skin:string;jersey:string};
type Team={id:string;name:string;short:string;primary:string;secondary:string;strength:string};
type Delivery='idle'|'runup'|'released'|'resolved'|'finished';
type MatchState={runs:number;wickets:number;balls:number;target:number;delivery:Delivery;swipeStart?:{x:number;y:number;time:number}};
type Rig={root:TransformNode;body:TransformNode;head:TransformNode;ls:TransformNode;le:TransformNode;rs:TransformNode;re:TransformNode;lh:TransformNode;lk:TransformNode;rh:TransformNode;rk:TransformNode;batPivot?:TransformNode;primary:StandardMaterial;accent:StandardMaterial;helmet:StandardMaterial;skin:StandardMaterial};

const captains:Captain[]=[
  {id:'ace',name:'Ace',style:'Balanced',skin:'#d59a6f',jersey:'#18a9e6'},
  {id:'blaze',name:'Blaze',style:'Power Hitter',skin:'#9b5b39',jersey:'#ef5a3d'},
  {id:'nova',name:'Nova',style:'Timing Specialist',skin:'#f0c7a8',jersey:'#8f63ff'}
];
const teams:Team[]=[
  {id:'arrows',name:'Ahmedabad Arrows',short:'AA',primary:'#12a9e8',secondary:'#08294f',strength:'Balanced'},
  {id:'waves',name:'Mumbai Waves',short:'MW',primary:'#1d67ff',secondary:'#ffbd2e',strength:'Power batting'},
  {id:'royals',name:'Jaipur Royals',short:'JR',primary:'#8f52d9',secondary:'#f4c95d',strength:'Timing'},
  {id:'guardians',name:'Chennai Guardians',short:'CG',primary:'#f2c94c',secondary:'#1c4a9c',strength:'Control'}
];

export class CricketGame{
  private engine:Engine;private scene:Scene;private camera:ArcRotateCamera;private shadow:ShadowGenerator;
  private batter!:Rig;private bowler!:Rig;private keeper!:Rig;private fielders:Rig[]=[];private ball!:Mesh;
  private captain=captains[0];private team=teams[0];private screen:'opening'|'captain'|'team'|'match'|'result'='opening';
  private state:MatchState={runs:0,wickets:0,balls:0,target:12,delivery:'idle'};private lastFrame=performance.now();private timer=0;private message='';
  private ballOrigin=new Vector3(0,2.1,19);private ballVelocity=new Vector3();private swipeDirection=new Vector3(0,0,1);private shotPower=0;

  constructor(private canvas:HTMLCanvasElement,private overlay:HTMLDivElement){
    this.engine=new Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,antialias:true},true);
    this.engine.setHardwareScalingLevel(Math.max(1,Math.min(1.55,window.devicePixelRatio/1.3)));
    this.scene=new Scene(this.engine);this.scene.clearColor=new Color4(.48,.8,.96,1);
    this.camera=new ArcRotateCamera('camera',Math.PI/2,1.08,34,new Vector3(0,3.7,0),this.scene);this.camera.inputs.clear();this.camera.lowerRadiusLimit=30;this.camera.upperRadiusLimit=38;
    const sun=new DirectionalLight('sun',new Vector3(-.4,-1,-.35),this.scene);sun.position=new Vector3(18,40,25);sun.intensity=2.2;
    new HemisphericLight('hemi',new Vector3(0,1,0),this.scene).intensity=1.15;
    this.shadow=new ShadowGenerator(1024,sun);this.shadow.useBlurExponentialShadowMap=true;this.shadow.blurKernel=24;
    this.buildStadium();this.buildCharacters();this.bindInput();
  }

  start(){this.renderUI();this.engine.runRenderLoop(()=>{const n=performance.now(),dt=Math.min(.033,(n-this.lastFrame)/1000);this.lastFrame=n;this.update(dt);this.scene.render()});addEventListener('resize',()=>this.engine.resize())}
  private mat(name:string,color:string){const m=new StandardMaterial(name,this.scene);m.diffuseColor=Color3.FromHexString(color);m.specularColor=new Color3(.14,.14,.14);return m}
  private part(name:string,parent:TransformNode,kind:'box'|'sphere'|'capsule'|'cylinder',size:Vector3,pos:Vector3,mat:StandardMaterial){
    let mesh:Mesh;if(kind==='box')mesh=MeshBuilder.CreateBox(name,{width:size.x,height:size.y,depth:size.z},this.scene);else if(kind==='sphere'){mesh=MeshBuilder.CreateSphere(name,{diameter:1,segments:16},this.scene);mesh.scaling.copyFrom(size)}else if(kind==='capsule')mesh=MeshBuilder.CreateCapsule(name,{height:size.y,radius:size.x,tessellation:16},this.scene);else mesh=MeshBuilder.CreateCylinder(name,{height:size.y,diameterTop:size.x,diameterBottom:size.z||size.x,tessellation:16},this.scene);
    mesh.parent=parent;mesh.position.copyFrom(pos);mesh.material=mat;this.shadow.addShadowCaster(mesh);return mesh
  }

  private buildStadium(){
    const grass=MeshBuilder.CreateGround('grass',{width:66,height:48},this.scene);grass.material=this.mat('grassMat','#2d9b52');grass.receiveShadows=true;
    const pitch=MeshBuilder.CreateGround('pitch',{width:7,height:24},this.scene);pitch.position.y=.03;pitch.material=this.mat('pitchMat','#c9a66b');
    const boundary=MeshBuilder.CreateTorus('boundary',{diameter:54,thickness:.18,tessellation:96},this.scene);boundary.rotation.x=Math.PI/2;boundary.position.y=.1;boundary.scaling.z=.72;boundary.material=this.mat('ropeMat','#f4f6f8');
    for(let side=-1;side<=1;side+=2){const stand=MeshBuilder.CreateBox(`stand${side}`,{width:64,height:8,depth:7},this.scene);stand.position.set(0,4.2,side*28);stand.material=this.mat(`standMat${side}`,side>0?'#17335f':'#6d2a72');for(let r=0;r<3;r++)for(let i=-12;i<=12;i++){const c=MeshBuilder.CreateSphere(`crowd-${side}-${r}-${i}`,{diameter:.5,segments:6},this.scene);c.position.set(i*2.2,2.3+r*1.5,side*(24.8+r*.35));c.material=this.mat(`cm-${side}-${r}-${i}`,['#ffd166','#ef476f','#06d6a0','#4cc9f0'][Math.abs(i+r)%4])}}
    for(const z of[-9.6,9.6])for(const x of[-.55,0,.55]){const s=MeshBuilder.CreateCylinder(`stump-${z}-${x}`,{height:2.5,diameter:.13},this.scene);s.position.set(x,1.25,z);s.material=this.mat(`sm-${z}-${x}`,'#f4e6b8')}
  }

  private createRig(name:string,pos:Vector3,jersey:string,skinTone:string,role:'batter'|'bowler'|'keeper'|'fielder'):Rig{
    const root=new TransformNode(name,this.scene);root.position.copyFrom(pos);const body=new TransformNode(`${name}-body`,this.scene);body.parent=root;
    const primary=this.mat(`${name}-primary`,jersey),secondary=this.mat(`${name}-secondary`,role==='batter'||role==='keeper'?'#f3f6fb':'#20324f'),accent=this.mat(`${name}-accent`,role==='batter'?'#ffd74a':'#17335f'),skin=this.mat(`${name}-skin`,skinTone),dark=this.mat(`${name}-dark`,'#172033'),white=this.mat(`${name}-white`,'#fff'),helmet=this.mat(`${name}-helmet`,role==='keeper'?'#d9a31d':'#244581'),grill=this.mat(`${name}-grill`,'#d7dde2'),pad=this.mat(`${name}-pad`,'#f4f1df');
    this.part(`${name}-hips`,body,'box',new Vector3(1.55,.72,1.25),new Vector3(0,1.8,0),secondary);
    const torso=this.part(`${name}-torso`,body,'capsule',new Vector3(.88,2.75,0),new Vector3(0,3.62,0),primary);torso.scaling.x=1.08;
    this.part(`${name}-belly`,body,'sphere',new Vector3(1.56,1.34,1.25),new Vector3(0,3.2,.06),primary);
    const stripe=this.part(`${name}-stripe`,body,'box',new Vector3(1.8,.24,1.2),new Vector3(0,3.55,-.78),accent);stripe.rotation.x=.08;
    const neck=new TransformNode(`${name}-neck`,this.scene);neck.parent=body;neck.position.set(0,5.08,.02);this.part(`${name}-neckMesh`,neck,'cylinder',new Vector3(.3,.46,.3),new Vector3(0,.18,0),skin);
    const head=new TransformNode(`${name}-head`,this.scene);head.parent=neck;head.position.set(0,.7,.02);
    const face=this.part(`${name}-face`,head,'sphere',new Vector3(1.14,1.28,1.08),Vector3.Zero(),skin);face.scaling.y=1.1;
    this.part(`${name}-jaw`,head,'sphere',new Vector3(.98,.78,.98),new Vector3(0,-.56,.1),skin);
    for(const x of[-.34,.34]){this.part(`${name}-ew${x}`,head,'sphere',new Vector3(.34,.2,.14),new Vector3(x,.2,-.96),white);this.part(`${name}-e${x}`,head,'sphere',new Vector3(.11,.11,.11),new Vector3(x,.19,-1.06),dark)}
    this.part(`${name}-nose`,head,'sphere',new Vector3(.18,.2,.2),new Vector3(0,-.03,-1.04),skin);this.part(`${name}-mouth`,head,'box',new Vector3(.52,.07,.08),new Vector3(0,-.52,-1.01),this.mat(`${name}-mouthMat`,'#7f342e'));
    if(role==='batter'||role==='keeper'){const top=this.part(`${name}-helmetTop`,head,'sphere',new Vector3(1.25,.84,1.2),new Vector3(0,.82,.02),helmet);top.scaling.y=.72;this.part(`${name}-helmetSide`,head,'box',new Vector3(1.95,.76,1.58),new Vector3(0,.36,.14),helmet);const peak=this.part(`${name}-peak`,head,'box',new Vector3(1.28,.16,.7),new Vector3(0,.28,-1.03),helmet);peak.rotation.x=.14;for(const x of[-.54,0,.54])this.part(`${name}-grill${x}`,head,'cylinder',new Vector3(.05,1.28,.05),new Vector3(x,-.14,-1.23),grill);this.part(`${name}-crossbar`,head,'box',new Vector3(1.14,.08,.08),new Vector3(0,.34,-1.2),grill)}else{const cap=this.part(`${name}-cap`,head,'sphere',new Vector3(1.18,.64,1.14),new Vector3(0,.7,.06),helmet);cap.scaling.y=.6;const peak=this.part(`${name}-capPeak`,head,'box',new Vector3(1.1,.15,.66),new Vector3(0,.42,-1.02),helmet);peak.rotation.x=.12}
    const ls=new TransformNode(`${name}-ls`,this.scene),rs=new TransformNode(`${name}-rs`,this.scene),le=new TransformNode(`${name}-le`,this.scene),re=new TransformNode(`${name}-re`,this.scene);ls.parent=rs.parent=body;ls.position.set(-1.02,4.5,.05);rs.position.set(1.02,4.5,.05);le.parent=ls;re.parent=rs;
    for(const[s,sh,el]of[['l',ls,le],['r',rs,re]]as const){this.part(`${name}-${s}Upper`,sh,'capsule',new Vector3(.28,1.66,0),new Vector3(0,-.7,0),primary);el.position.set(0,-1.42,0);this.part(`${name}-${s}Lower`,el,'capsule',new Vector3(.24,1.48,0),new Vector3(0,-.62,0),role==='batter'||role==='keeper'?white:skin);this.part(`${name}-${s}Hand`,el,'sphere',new Vector3(.34,.34,.34),new Vector3(0,-1.4,0),role==='batter'||role==='keeper'?white:skin)}
    const lh=new TransformNode(`${name}-lh`,this.scene),rh=new TransformNode(`${name}-rh`,this.scene),lk=new TransformNode(`${name}-lk`,this.scene),rk=new TransformNode(`${name}-rk`,this.scene);lh.parent=rh.parent=body;lh.position.set(-.48,1.52,0);rh.position.set(.48,1.52,0);lk.parent=lh;rk.parent=rh;
    for(const[s,h,k]of[['l',lh,lk],['r',rh,rk]]as const){this.part(`${name}-${s}Thigh`,h,'capsule',new Vector3(.34,1.86,0),new Vector3(0,-.78,0),secondary);k.position.set(0,-1.58,0);this.part(`${name}-${s}Shin`,k,'capsule',new Vector3(.29,1.62,0),new Vector3(0,-.68,0),role==='batter'||role==='keeper'?pad:secondary);const shoe=this.part(`${name}-${s}Shoe`,k,'box',new Vector3(.7,.3,1.08),new Vector3(0,-1.42,-.18),dark);shoe.rotation.x=-.08}
    let batPivot:TransformNode|undefined;if(role==='batter'){batPivot=new TransformNode(`${name}-batPivot`,this.scene);batPivot.parent=re;batPivot.position.set(-.02,-1.26,-.02);const bat=MeshBuilder.CreateBox(`${name}-bat`,{width:.46,height:4.2,depth:.22},this.scene);bat.parent=batPivot;bat.position.set(-.2,-1.4,-.18);bat.rotation.set(.06,0,-.42);bat.material=this.mat(`${name}-batMat`,'#e8b96e');this.shadow.addShadowCaster(bat)}
    const rig={root,body,head,ls,le,rs,re,lh,lk,rh,rk,batPivot,primary,accent,helmet,skin};if(role==='batter')this.poseBatter(rig);else if(role==='keeper')this.poseKeeper(rig);else if(role==='fielder')this.poseFielder(rig);else this.poseBowler(rig);return rig
  }

  private poseBatter(r:Rig){r.ls.rotation.set(-.18,.16,.62);r.le.rotation.set(-.14,0,.52);r.rs.rotation.set(-.72,-.1,-.2);r.re.rotation.set(-.2,0,-.44);r.lh.rotation.set(0,0,-.09);r.rh.rotation.set(0,0,.09);r.lk.rotation.set(.04,0,0);r.rk.rotation.set(-.02,0,0);r.batPivot?.rotation.set(.14,-.2,-.72)}
  private poseKeeper(r:Rig){r.ls.rotation.set(-.86,0,.4);r.rs.rotation.set(-.86,0,-.4);r.le.rotation.set(-.22,0,.3);r.re.rotation.set(-.22,0,-.3);r.lh.rotation.set(.24,0,-.16);r.rh.rotation.set(.24,0,.16);r.lk.rotation.set(-.34,0,0);r.rk.rotation.set(-.34,0,0);r.body.position.y=-.36}
  private poseFielder(r:Rig){r.ls.rotation.set(.08,0,.12);r.rs.rotation.set(-.08,0,-.12);r.le.rotation.set(.02,0,.08);r.re.rotation.set(.02,0,-.08)}
  private poseBowler(r:Rig){r.ls.rotation.set(.12,0,.06);r.rs.rotation.set(-.12,0,-.06);r.le.rotation.set(.02,0,.06);r.re.rotation.set(.02,0,-.06);r.lh.rotation.set(.02,0,-.02);r.rh.rotation.set(-.02,0,.02)}

  private buildCharacters(){this.batter=this.createRig('batter',new Vector3(0,0,-7.6),this.captain.jersey,this.captain.skin,'batter');this.batter.root.rotation.y=Math.PI;this.bowler=this.createRig('bowler',new Vector3(0,0,14.5),'#f05a3b','#9a5a38','bowler');this.keeper=this.createRig('keeper',new Vector3(0,0,-11.2),'#ffc93c','#c58458','keeper');this.keeper.root.scaling.setAll(.92);for(const[x,z]of[[-14,-2],[14,-2],[-18,10],[18,10],[-10,19],[10,19]]as const){const f=this.createRig(`fielder-${x}-${z}`,new Vector3(x,0,z),'#f05a3b','#c58458','fielder');f.root.scaling.setAll(.72);f.root.rotation.y=Math.atan2(-x,-z);this.fielders.push(f)}this.ball=MeshBuilder.CreateSphere('ball',{diameter:.48,segments:16},this.scene);const bm=new PBRMaterial('ballMat',this.scene);bm.albedoColor=Color3.FromHexString('#b51528');bm.roughness=.42;this.ball.material=bm;this.ball.position.copyFrom(this.ballOrigin);this.shadow.addShadowCaster(this.ball)}

  private bindInput(){this.overlay.addEventListener('click',e=>{const t=e.target as HTMLElement,a=t.dataset.action,v=t.dataset.value;if(!a)return;if(a==='start')this.screen='captain';if(a==='captain'&&v){this.captain=captains.find(c=>c.id===v)??captains[0];this.batter.skin.diffuseColor=Color3.FromHexString(this.captain.skin);this.screen='team'}if(a==='team'&&v){this.team=teams.find(x=>x.id===v)??teams[0];this.applySelection();this.startMatch()}if(a==='retry')this.startMatch();if(a==='home')this.screen='opening';this.renderUI()});this.canvas.addEventListener('touchstart',e=>this.beginSwipe(e.touches[0].clientX,e.touches[0].clientY),{passive:true});this.canvas.addEventListener('touchend',e=>{const t=e.changedTouches[0];this.endSwipe(t.clientX,t.clientY)},{passive:true});this.canvas.addEventListener('mousedown',e=>this.beginSwipe(e.clientX,e.clientY));this.canvas.addEventListener('mouseup',e=>this.endSwipe(e.clientX,e.clientY))}
  private beginSwipe(x:number,y:number){if(this.screen==='match')this.state.swipeStart={x,y,time:performance.now()}}
  private endSwipe(x:number,y:number){if(!this.state.swipeStart||this.state.delivery!=='released')return;const dx=x-this.state.swipeStart.x,dy=y-this.state.swipeStart.y,len=Math.hypot(dx,dy);if(len<18)return;this.swipeDirection.set(dx/Math.max(1,Math.abs(dx)+Math.abs(dy)),Math.max(.15,-dy/160),1).normalize();this.shotPower=Math.min(1,len/220);this.resolveShot(performance.now()-this.state.swipeStart.time);this.state.swipeStart=undefined}
  private applySelection(){this.batter.primary.diffuseColor=Color3.FromHexString(this.team.primary);this.batter.accent.diffuseColor=Color3.FromHexString(this.team.secondary);this.batter.helmet.diffuseColor=Color3.FromHexString(this.team.secondary)}
  private startMatch(){this.screen='match';this.state={runs:0,wickets:0,balls:0,target:12,delivery:'idle'};this.message='Swipe when the ball reaches you';this.ball.position.copyFrom(this.ballOrigin);this.resetPoses();this.renderUI();setTimeout(()=>this.beginDelivery(),900)}
  private beginDelivery(){if(this.screen!=='match'||this.state.balls>=6||this.state.wickets>=2)return;this.state.delivery='runup';this.timer=0;this.message='Bowler running in…';this.bowler.root.position.z=18;this.ball.position.copyFrom(this.ballOrigin);this.poseBowler(this.bowler);this.renderUI()}
  private resolveShot(reaction:number){if(this.state.delivery!=='released')return;const d=Math.abs(this.ball.position.z+7.2),timing=Math.max(0,1-d/5.2),quality=timing*.72+this.shotPower*.32-Math.abs(this.swipeDirection.x)*.1;this.state.delivery='resolved';if(quality<.2||reaction>900){this.state.wickets++;this.message=quality<.1?'BOWLED!':'Caught behind!';this.ballVelocity.set(0,.4,-7);this.animateMiss()}else{const runs=quality>.78?6:quality>.58?4:quality>.42?2:1;this.state.runs+=runs;this.message=runs===6?'SIX! Perfect timing':runs===4?'FOUR! Beautiful shot':`${runs} run${runs>1?'s':''}`;this.ballVelocity.set(this.swipeDirection.x*(13+9*this.shotPower),8+10*this.shotPower,17+10*this.shotPower);this.animateShot()}this.renderUI()}
  private animateShot(){const start=performance.now(),dir=this.swipeDirection.x,tick=()=>{const p=Math.min(1,(performance.now()-start)/520),s=Math.sin(p*Math.PI);this.batter.root.rotation.y=Math.PI-dir*.38*s;this.batter.rs.rotation.x=-.72-1.22*s;this.batter.rs.rotation.z=-.2-.55*s;this.batter.re.rotation.z=-.44-.42*s;this.batter.ls.rotation.x=-.18-.8*s;this.batter.ls.rotation.z=.62+.42*s;this.batter.le.rotation.z=.52+.3*s;this.batter.lh.rotation.z=-.09-.1*s;this.batter.rh.rotation.z=.09+.15*s;if(this.batter.batPivot)this.batter.batPivot.rotation.z=-.72-1.05*s;p<1?requestAnimationFrame(tick):this.resetPoses()};requestAnimationFrame(tick)}
  private animateMiss(){const start=performance.now(),tick=()=>{const p=Math.min(1,(performance.now()-start)/560),s=Math.sin(p*Math.PI);this.batter.head.rotation.z=.16*s;this.batter.rs.rotation.z=-.2+.2*s;this.batter.body.rotation.x=-.05*s;p<1?requestAnimationFrame(tick):this.resetPoses()};requestAnimationFrame(tick)}
  private resetPoses(){this.batter.root.rotation.set(0,Math.PI,0);this.batter.body.rotation.set(0,0,0);this.batter.body.position.set(0,0,0);this.batter.head.rotation.set(0,0,0);this.poseBatter(this.batter);this.bowler.root.rotation.set(0,0,0);this.bowler.body.position.set(0,0,0);this.poseBowler(this.bowler);this.keeper.body.position.set(0,-.36,0);this.poseKeeper(this.keeper)}

  private update(dt:number){if(this.screen!=='match')return;this.timer+=dt;this.batter.head.rotation.y=Math.sin(performance.now()*.002)*.035;if(this.state.delivery==='runup'){this.bowler.root.position.z-=dt*8.8;const run=Math.sin(this.timer*15);this.bowler.ls.rotation.x=run*.9;this.bowler.rs.rotation.x=-run*.9;this.bowler.le.rotation.x=-run*.2;this.bowler.re.rotation.x=run*.2;this.bowler.lh.rotation.x=-run*.72;this.bowler.rh.rotation.x=run*.72;this.bowler.body.position.y=Math.abs(run)*.08;if(this.bowler.root.position.z<=11.7){this.state.delivery='released';this.bowler.rs.rotation.x=-2.2;this.bowler.rs.rotation.z=-.3;this.bowler.ls.rotation.x=.72;this.bowler.le.rotation.x=.3;this.bowler.body.position.y=0;this.ball.position.set(0,2.15,10.4);this.ballVelocity.set((Math.random()-.5)*.7,.35,-17.8);this.message='SWIPE NOW';this.renderUI()}}else if(this.state.delivery==='released'){this.ballVelocity.y-=9.8*dt;this.ball.position.addInPlace(this.ballVelocity.scale(dt));this.ball.rotation.x+=dt*18;if(this.ball.position.y<.3&&this.ball.position.z>-5){this.ball.position.y=.3;this.ballVelocity.y=Math.abs(this.ballVelocity.y)*.62}if(this.ball.position.z<-10.5){this.state.wickets++;this.state.delivery='resolved';this.message='MISSED — bowled!';this.animateMiss();this.renderUI()}}else if(this.state.delivery==='resolved'){this.ballVelocity.y-=9.8*dt;this.ball.position.addInPlace(this.ballVelocity.scale(dt));if(this.timer>2.8)this.completeBall()}}
  private completeBall(){this.state.balls++;this.state.delivery='idle';this.timer=0;this.ball.position.copyFrom(this.ballOrigin);this.poseBowler(this.bowler);this.bowler.body.position.y=0;const won=this.state.runs>=this.state.target,ended=won||this.state.balls>=6||this.state.wickets>=2;if(ended){this.screen='result';this.state.delivery='finished';this.renderUI()}else{this.message=`${6-this.state.balls} ball${6-this.state.balls===1?'':'s'} remaining`;this.renderUI();setTimeout(()=>this.beginDelivery(),800)}}

  private renderUI(){
    if(this.screen==='opening'){this.overlay.innerHTML=`<section class="screen opening"><div class="hero-card"><div class="logo-ball">🏏</div><p class="eyebrow">DEVANG GAMES</p><h1>Cricket Captain 3D</h1><p>Play with upgraded full 3D cartoon characters. Pick your captain, choose your team, and chase the target.</p><button data-action="start" class="primary">Play Now</button></div></section>`;return}
    if(this.screen==='captain'){this.overlay.innerHTML=`<section class="screen selection"><div class="selection-card"><p class="eyebrow">STEP 1 OF 2</p><h2>Choose your captain</h2><div class="card-grid">${captains.map(c=>`<button class="choice" data-action="captain" data-value="${c.id}"><span class="avatar" style="--jersey:${c.jersey};--skin:${c.skin}"></span><strong>${c.name}</strong><small>${c.style}</small></button>`).join('')}</div></div></section>`;return}
    if(this.screen==='team'){this.overlay.innerHTML=`<section class="screen selection"><div class="selection-card wide"><p class="eyebrow">STEP 2 OF 2</p><h2>Select your team</h2><div class="team-grid">${teams.map(t=>`<button class="team-choice" data-action="team" data-value="${t.id}" style="--primary:${t.primary};--secondary:${t.secondary}"><span class="team-badge">${t.short}</span><strong>${t.name}</strong><small>${t.strength}</small></button>`).join('')}</div></div></section>`;return}
    if(this.screen==='match'){this.overlay.innerHTML=`<div class="hud"><div class="score-card"><span>${this.team.short}</span><strong>${this.state.runs}/${this.state.wickets}</strong><small>${Math.floor(this.state.balls/6)}.${this.state.balls%6} overs</small></div><div class="target-card">TARGET <strong>${this.state.target}</strong><small>${Math.max(0,this.state.target-this.state.runs)} needed</small></div><div class="message ${this.message.includes('SWIPE')?'pulse':''}">${this.message}</div><div class="swipe-guide"><span>↖</span><span>↑</span><span>↗</span><small>Swipe to play a shot</small></div></div>`;return}
    const won=this.state.runs>=this.state.target;this.overlay.innerHTML=`<section class="screen result"><div class="result-card"><div class="result-icon">${won?'🏆':'🏏'}</div><p class="eyebrow">MATCH RESULT</p><h2>${won?'Victory!':'So close!'}</h2><p>${this.team.name} scored <strong>${this.state.runs}/${this.state.wickets}</strong> in ${this.state.balls} balls.</p><div class="result-actions"><button data-action="retry" class="primary">Play Again</button><button data-action="home" class="secondary">Home</button></div></div></section>`
  }
}
